GET http://localhost:8080/devops_starter_war_exploded/api/xxx/all

###

GET http://localhost:8080/devops_starter_war_exploded/api/xxx/1

###

POST http://localhost:8080/devops_starter_war_exploded/api/xxx
Content-Type: application/json

{
  "firstName": "Karl",
  "lastName": "Johannson",
  "phone": "123456"
}

###

DELETE http://localhost:8080/devops_starter_war_exploded/api/xxx/2